### ISSUE TITLE
implement decorate on $controller() 

### ISSUE THREAD

**Issue by christopherthielen** [christopherthielen/angular-360-no-scope#6]
I seem to have forgotten to hook up $controller() service fn decoration, which is used by ui-router, for example.

https://github.com/christopherthielen/angular-360-no-scope/blob/master/angular-360-no-scope.js#L16

**Comment by trumbitta** [comment]
Ouch! Does this mean I can't use this awesome piece of awesomeness with ui-router?

**Comment by christopherthielen** [comment]
Yes, it does. It shouldn't be too difficult to implement. I didn't know anyone was using this thing :)
